yamlproject:
  meta:
    name: YAMLConfig
    createdBy: Vijay Tolani
  contributors:
    - Vijay Tolani
    - PlaceHolder 1
    - PlaceHolder 2
  accountHolders: 
    - holderName: Vijay 
      acccountType: Savings
      accountId: 1
      bankName: ICICI
    - holderName: Pia 
      acccountType: Current
      accountId: 2
      bankName: HDFC
  activecheck:
    1: true
    2: false
    3: true
      